version: '2'
services:
    payara-full:
        build: mypayara-full
        environment:
           - ADMIN_PASSWORD=admin
        ports:
            - "8080:8080"
            - "8181:8181"
            - "4848:4848"
        volumes:
          # application to deploy at startup
            - "./data/payara/deployments:/opt/payara/deployments"
        depends_on:
            - db

    db:
        image: postgres:13.1-alpine
        ports:
          - "5432:5432"
        environment:
            POSTGRES_PASSWORD: glassfishdbpassword
            POSTGRES_USER: glassfish
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ./data/pgdata:/var/lib/postgresql/data/pgdata
