version: '2'
services:
    payara-full:
        build: mypayara-full
        environment:
           - ADMIN_PASSWORD=admin
        ports:
            - "8080:8080"
            - "4848:4848"
        entrypoint:
            - /opt/payara41/bin/asadmin
            - start-domain
            - -v
        volumes:
          # application to deploy at startup
            - "./data/payara/deployments:/opt/payara41/deployments"
          # autodeploy (discouraged : no parameters, needs write access)
            - "./data/payara/autodeploy:/opt/payara41/glassfish/domains/domain1/autodeploy"
            
            - "./payara-init.sh:/usr/local/bin/payara-init.sh"
        depends_on:
            - db

    db:
        image: oscarfonts/h2:1.4.199
        ports:
            - "1521:1521"
            - "8081:81"
        environment:
            H2_OPTIONS: '-ifNotExists'
        volumes:
            - ./data/h2data:/opt/h2-data
